// Code generated by tools/codegen/gen-formats.mjs from tools/codegen/formats.json; DO NOT EDIT.

package domain

// SupportedFormats is the canonical set of comic formats ComicHub reads.
var SupportedFormats = []string{"cbz", "cbr", "cb7", "cbt", "pdf"}

// ArchiveFormats are the container-based formats (everything except PDF).
var ArchiveFormats = []string{"cbz", "cbr", "cb7", "cbt"}
