// Code generated by tools/codegen/gen-formats.mjs from tools/codegen/formats.json; DO NOT EDIT.
export const SUPPORTED_FORMATS = ['cbz', 'cbr', 'cb7', 'cbt', 'pdf'] as const;
export const ARCHIVE_FORMATS = ['cbz', 'cbr', 'cb7', 'cbt'] as const;
export type ComicFormat = (typeof SUPPORTED_FORMATS)[number];
