#!/usr/bin/env node
// Generates the per-language supported-format constants from formats.json so the
// TypeScript, Rust, and Go definitions can never drift.
//
//   node tools/codegen/gen-formats.mjs            # write generated files
//   node tools/codegen/gen-formats.mjs --check    # fail (exit 1) if anything is stale
//
// Also validates that the reader's tauri.conf.json file associations match the formats
// marked `associate: true`. Zero dependencies (Node stdlib only).

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const check = process.argv.includes('--check');

const spec = JSON.parse(readFileSync(resolve(here, 'formats.json'), 'utf8'));
const formats = spec.formats;
const supported = formats.map((f) => f.ext);
const archive = formats.filter((f) => f.kind === 'archive').map((f) => f.ext);
const associated = formats.filter((f) => f.associate).map((f) => f.ext);

const NOTE =
  'Code generated by tools/codegen/gen-formats.mjs from tools/codegen/formats.json; DO NOT EDIT.';

const ts = (a) => a.map((x) => `'${x}'`).join(', ');
const q = (a) => a.map((x) => `"${x}"`).join(', ');

const targets = [
  {
    path: 'packages/reader-core/src/formats.gen.ts',
    content: `// ${NOTE}
export const SUPPORTED_FORMATS = [${ts(supported)}] as const;
export const ARCHIVE_FORMATS = [${ts(archive)}] as const;
export type ComicFormat = (typeof SUPPORTED_FORMATS)[number];
`,
  },
  {
    path: 'apps/reader/src-tauri/src/formats_gen.rs',
    content: `// ${NOTE}
pub const SUPPORTED_EXTENSIONS: &[&str] = &[${q(supported)}];
`,
  },
  {
    path: 'server/internal/domain/formats_gen.go',
    content: `// ${NOTE}

package domain

// SupportedFormats is the canonical set of comic formats ComicHub reads.
var SupportedFormats = []string{${q(supported)}}

// ArchiveFormats are the container-based formats (everything except PDF).
var ArchiveFormats = []string{${q(archive)}}
`,
  },
];

const norm = (s) => s.replace(/\r\n/g, '\n');
const tryRead = (p) => {
  try {
    return readFileSync(p, 'utf8');
  } catch {
    return '';
  }
};

const stale = [];
for (const t of targets) {
  const abs = resolve(repoRoot, t.path);
  if (norm(tryRead(abs)) !== norm(t.content)) {
    stale.push(t.path);
    if (!check) writeFileSync(abs, t.content);
  }
}

// Validate reader file associations against the `associate: true` set.
const confPath = 'apps/reader/src-tauri/tauri.conf.json';
const conf = JSON.parse(readFileSync(resolve(repoRoot, confPath), 'utf8'));
const confExts = (conf.bundle?.fileAssociations ?? []).flatMap((fa) => fa.ext ?? []).sort();
const wantExts = [...associated].sort();
const assocMismatch = JSON.stringify(confExts) !== JSON.stringify(wantExts);

if (assocMismatch) {
  console.error(
    `\n✗ ${confPath} fileAssociations [${confExts.join(', ')}] != associated formats [${wantExts.join(
      ', ',
    )}].\n  Update the fileAssociations ext arrays to match formats.json (associate: true).`,
  );
}

if (check) {
  if (stale.length || assocMismatch) {
    if (stale.length) {
      console.error(`\n✗ Stale generated files (run \`pnpm codegen\`):\n  - ${stale.join('\n  - ')}`);
    }
    process.exit(1);
  }
  console.log('✓ generated format files are up to date');
} else {
  if (stale.length) {
    console.log(`Generated:\n  - ${stale.join('\n  - ')}`);
  } else {
    console.log('Generated format files already up to date');
  }
  if (assocMismatch) process.exit(1);
}
